public class Calculator {
    public static integer add(Integer number1, integer number2){
        return number1 + number2;
    }
    public static integer subtract(Integer number1, integer number2){
        return number1 - number2;
    }
    public static integer multiply(Integer number1, integer number2){
        return number1 * number2;
    }
    public static integer divide(Integer number1, integer number2){
        return number1 / number2;
    }
}